name: Rust CI
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Install Rust
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: clippy, rustfmt

      # 3. Cache cargo registry & build artifacts
      - name: Cache Cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: cargo-registry-windows
      
      - name: Cache Cargo build
        uses: actions/cache@v3
        with:
          path: target
          key: cargo-build-windows
      
      - name: Build
        run: cargo build --profile smaller-release --verbose

      - name: Run tests
        run: cargo test --verbose 

      - name: Run Cargo Clippy
        run: cargo clippy

      - name: Run Cargo Format
        run: cargo fmt --check

      - name: Run Cargo Doc
        run: cargo doc --no-deps

      - name: Archive binary
        uses: actions/upload-artifact@v4
        with:
          name: pace26checker-win.exe
          path: target/smaller-release/checker.exe






